config/routes.rb
SecretShare::Application.routes.draw do
  root :to => 'directories#index'
  resources :photos do
    member do
      get 'inline_thumbnail'
      get 'inline_image'
      get 'original_image'
    end
  end

  resources :directories do
    post 'scan', :on => :collection
    resources :photos do
      member do
        get 'inline_thumbnail'
        get 'inline_image'
        get 'original_image'
      end
    end
  end

  resources :baskets do
    post 'download' , :on => :member
    resources :photos do
      member do
        get 'inline_thumbnail'
        get 'inline_image'
        get 'original_image'
      end
    end
  end

  resource :pickings, :only => %w[create]

end

app/models/directory.rb
class Directory < ActiveRecord::Base
  has_many :photos
  attr_accessible :path, :modified_at, :is_ready_for_detail

  def got_ready_for_detail
    self.is_ready_for_detail = true
    save!
  end
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  # GET /directories
  # GET /directories.json
  def index
    @directories = Directory.order("path").all
    @isScanning = false
    if @directories.size > 0
      @isScanning = @directories.select { |d| !d.is_ready_for_detail }.size > 0
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @directories }
    end
  end

  # GET /directories/1
  # GET /directories/1.json
  def show
    @directory = Directory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @directory }
    end
  end

  # GET /directories/new
  # GET /directories/new.json
  def new
    @directory = Directory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @directory }
    end
  end

  # GET /directories/1/edit
  def edit
    @directory = Directory.find(params[:id])
  end

  # POST /directories/scan
  def scan
    root_dir = AppConfig[:root_directory]
    root_dir += "/" unless /\/$/ =~ root_dir

    sub_dir_names = []
    Dir::glob(root_dir + "**/*.{jpg,JPG}").each do |f|
      sub_dir_names << File.dirname(f).sub(root_dir, "")
    end
    sub_dir_names.uniq!

    sub_dir_names.each do |path|
      modified_time = File.mtime(root_dir + path)
      directory = Directory.where(:path => path).first

      # has not created target model yet
      if !directory
        directory = Directory.new(:path => path, :modified_at => modified_time, :is_ready_for_detail => false)
        if !directory.save
          #TODO error code
        end
        create_photos_in_sub_directory(root_dir + path, directory.id)
        directory.delay.got_ready_for_detail # pushed this job after jobs which create photos
      end

      # update
      if modified_time != directory.modified_at
        # destroy all once!
        target_dir_photos = Photo.where(:directory_id => directory.id)
        target_dir_photos.destroy_all
        directory.update_attributes(:is_ready_for_detail => false)

        create_photos_in_sub_directory(root_dir + path, directory.id)
        directory.delay.got_ready_for_detail # pushed this job after jobs which create photos
      end
    end

    respond_to do |format|
      format.html { redirect_to directories_url }
      format.json { head :ok }
    end
  end

  # POST /directories
  # POST /directories.json
  def create
    @directory = Directory.new(params[:directory])

    respond_to do |format|
      if @directory.save
        format.html { redirect_to @directory, notice: 'Directory was successfully created.' }
        format.json { render json: @directory, status: :created, location: @directory }
      else
        format.html { render action: "new" }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /directories/1
  # PUT /directories/1.json
  def update
    @directory = Directory.find(params[:id])

    respond_to do |format|
      if @directory.update_attributes(params[:directory])
        format.html { redirect_to @directory, notice: 'Directory was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directories/1
  # DELETE /directories/1.json
  def destroy
    @directory = Directory.find(params[:id])
    @directory.destroy

    respond_to do |format|
      format.html { redirect_to directories_url }
      format.json { head :ok }
    end
  end

  private

  def create_photos_in_sub_directory(full_path, directory_id)
    Dir::glob(full_path + "/*.{jpg,JPG}").each do |f|
      photo = Photo.new(:full_name => f, :directory_id => directory_id)
      if !photo.save
        #TODO error code
      end
      photo.delay.make_additional_data
    end
  end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/views/directories/_form.html.erb
<%= form_for(@directory) do |f| %>
  <% if @directory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory.errors.count, "error") %> prohibited this directory from being saved:</h2>

      <ul>
      <% @directory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :modified_at %><br />
    <%= f.datetime_select :modified_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directories/edit.html.erb
<h1>Editing directory</h1>

<%= render 'form' %>

<%= link_to 'Show', @directory %> |
<%= link_to 'Back', directories_path %>

app/views/directories/index.html.erb
<%- model_class = Directory.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>

<% if @isScanning %>
  <script type="text/javascript" language="javascript">
    setTimeout("location.reload()",10000);
  </script>
<% end %>

<p>
  <% if @isScanning %>
    Now is scanning directory...
  <% else %>
    <%= link_to 'Scan', [ :scan, :directories ], :method => :post, :class => 'btn btn-primary' %>
  <% end %>
</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:path) %></th>
      <th><%= model_class.human_attribute_name(:modified_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @directories.each do |directory| %>
      <tr>
        <td><%= directory.path %></td>
	<td><%= directory.modified_at.getlocal %></td>
        <td>
	  <% if directory.is_ready_for_detail %>
            <%= link_to 'Show', [ directory, :photos ], :class => 'btn btn-mini' %>
	  <% else %>
	    loading...
	  <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/directories/new.html.erb
<h1>New directory</h1>

<%= render 'form' %>

<%= link_to 'Back', directories_path %>

app/views/directories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Path:</b>
  <%= @directory.path %>
</p>

<p>
  <b>Modified at:</b>
  <%= @directory.modified_at %>
</p>


<%= link_to 'Edit', edit_directory_path(@directory) %> |
<%= link_to 'Back', directories_path %>