config/routes.rb
SecretShare::Application.routes.draw do
  root :to => 'directories#index'
  resources :photos do
    member do
      get 'inline_thumbnail'
      get 'inline_image'
      get 'original_image'
    end
  end

  resources :directories do
    post 'scan', :on => :collection
    resources :photos do
      member do
        get 'inline_thumbnail'
        get 'inline_image'
        get 'original_image'
      end
    end
  end

  resources :baskets do
    post 'download' , :on => :member
    resources :photos do
      member do
        get 'inline_thumbnail'
        get 'inline_image'
        get 'original_image'
      end
    end
  end

  resource :pickings, :only => %w[create]

end

app/models/basket.rb
class Basket < ActiveRecord::Base
  has_many :pickings
  has_many :photos, :through => :pickings
  attr_accessible :name
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  # GET /baskets/1/download
  def download
    @basket = Basket.find(params[:id])

    zip_tempfile = Tempfile.new([@basket.name, '.zip'])

    begin
      logger.debug("Zipfile name: " + zip_tempfile.path)
      input_filenames = @basket.photos.map { |p| p.full_name }
      input_filenames.uniq!
      Zip::OutputStream.open(zip_tempfile) {|zos|}
      Zip::File.open(zip_tempfile.path, Zip::File::CREATE) do |zipfile|
        input_filenames.each do |filename|
          zipfile.add(File.basename(filename), filename)
        end
      end
      zip_data = File.read(zip_tempfile.path)
      send_data(zip_data, :type => 'application/zip', :filename => File.basename(zip_tempfile.path))
    ensure
      zip_tempfile.close
      zip_tempfile.unlink
    end
  end

  # GET /baskets
  # GET /baskets.json
  def index
    @baskets = Basket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @baskets }
    end
  end

  # GET /baskets/1
  # GET /baskets/1.json
  def show
    @basket = Basket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @basket }
    end
  end

  # GET /baskets/new
  # GET /baskets/new.json
  def new
    @basket = Basket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @basket }
    end
  end

  # GET /baskets/1/edit
  def edit
    @basket = Basket.find(params[:id])
  end

  # POST /baskets
  # POST /baskets.json
  def create
    @basket = Basket.new(params[:basket])

    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: 'Basket was successfully created.' }
        format.json { render json: @basket, status: :created, location: @basket }
      else
        format.html { render action: "new" }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /baskets/1
  # PUT /baskets/1.json
  def update
    @basket = Basket.find(params[:id])

    respond_to do |format|
      if @basket.update_attributes(params[:basket])
        format.html { redirect_to @basket, notice: 'Basket was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baskets/1
  # DELETE /baskets/1.json
  def destroy
    @basket = Basket.find(params[:id])
    @basket.destroy

    respond_to do |format|
      format.html { redirect_to baskets_url }
      format.json { head :ok }
    end
  end
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/views/baskets/_form.html.erb
<%= form_for(@basket) do |f| %>
  <% if @basket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basket.errors.count, "error") %> prohibited this basket from being saved:</h2>

      <ul>
      <% @basket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/baskets/edit.html.erb
<h1>Editing basket</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.erb
<h1>Listing baskets</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @baskets.each do |basket| %>
  <tr>
    <td><%= basket.name %></td>
    <td><%= link_to 'Show', basket %></td>
    <td><%= link_to 'Edit', edit_basket_path(basket) %></td>
    <td><%= link_to 'Destroy', basket, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Basket', new_basket_path %>

app/views/baskets/new.html.erb
<h1>New basket</h1>

<%= render 'form' %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @basket.name %>
</p>


<%= link_to 'Edit', edit_basket_path(@basket) %> |
<%= link_to 'Back', baskets_path %>