config/routes.rb
SecretShare::Application.routes.draw do
  root :to => 'directories#index'
  resources :photos do
    member do
      get 'inline_thumbnail'
      get 'inline_image'
      get 'original_image'
    end
  end

  resources :directories do
    post 'scan', :on => :collection
    resources :photos do
      member do
        get 'inline_thumbnail'
        get 'inline_image'
        get 'original_image'
      end
    end
  end

  resources :baskets do
    post 'download' , :on => :member
    resources :photos do
      member do
        get 'inline_thumbnail'
        get 'inline_image'
        get 'original_image'
      end
    end
  end

  resource :pickings, :only => %w[create]

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :directory
  has_many :pickings
  has_many :baskets, :through => :pickings
  attr_accessible :full_name, :directory_id

  def read_original_time
    self.date_time_original = get_original_time_by_exif(self.full_name)
  end

  def create_medium_thumbnail
    img = make_thumbnail(self.full_name, 240.0)
    self.thumbnail_medium = img.to_blob
  end

  def create_small_thumbnail
    img = make_thumbnail(self.full_name, 80.0)
    self.thumbnail_small = img.to_blob
  end

  # makes all data which has not been set
  def make_additional_data
    if !self.date_time_original || !self.thumbnail_medium || !self.thumbnail_small
      img = Magick::ImageList.new(self.full_name)

      if !self.date_time_original
        self.date_time_original = get_original_time_by_exif(img)
      end

      if !self.thumbnail_medium
        thumbnail = make_thumbnail(img, 240.0)
        self.thumbnail_medium = thumbnail.to_blob
      end

      if !self.thumbnail_small
        thumbnail = make_thumbnail(img, 80.0)
        self.thumbnail_small = thumbnail.to_blob
      end
      save!
    end
  end

  private

  # 'DateTimeOriginal' means the time by which the photograph was taken.
  def get_original_time_by_exif(img)
    exif_time_str = img.get_exif_by_entry('DateTimeOriginal')[0][1]
    exif_time_str.sub!(/^(\d\d\d\d).(\d\d).(\d\d)/, '\1-\2-\3')
    original_time = Time.parse(exif_time_str)
  end

  def make_thumbnail(img, limit_width)
    scale = img.columns > limit_width ? limit_width / img.columns : 1.0
    out_img = img.auto_orient.thumbnail(scale)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    if params[:directory_id]
      @directory = Directory.find(params[:directory_id])
      @list_name = "Directory: " + @directory.path
      @photos = @directory.photos.order("date_time_original").all
    elsif params[:basket_id]
      @basket = Basket.find(params[:basket_id])
      @list_name = "Basket: " + @basket.name
      @photos = @basket.photos.order("date_time_original").all
    else
      @list_name = ""
      @photos = Photo.order("date_time_original").all
    end

    @baskets = Basket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :ok }
    end
  end

  def inline_thumbnail
    @photo = Photo.find(params[:id])

    @photo.make_additional_data
    @photo.save if @photo.changed?

    send_data(@photo.thumbnail_medium, :type => 'image/jpeg', :disposition => 'inline')
  end

  def inline_image
    @photo = Photo.find(params[:id])

    img = Magick::ImageList.new(@photo.full_name)
    scale = img.columns > 1024.0 ? 1024.0 / img.columns : 1.0
    out_img = img.auto_orient.resize(scale)

    send_data(out_img.to_blob, :type => 'image/jpeg', :disposition => 'inline')
  end

  def original_image
    @photo = Photo.find(params[:id])
    send_file(@photo.full_name, :type => 'image/jpeg', :disposition => 'inline')
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :directory_id %><br />
    <%= f.number_field :directory_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_list.html.erb
<h1><%= @list_name %></h1>
<ul class="thumbnails">
  <% @photos.each do |photo| %>
    <li class="thumbnail-item" data-toggle="tooltip" title="<%= File.basename(photo.full_name) %>, <%= photo.date_time_original.getlocal if photo.date_time_original %>">
      <div class="thumbnail">
	<span class="inline-thumbnail" id="photo<%= photo.id.to_s %>"><%= link_to image_tag(url_for(:action => 'inline_thumbnail', :id => photo.id)), photo %></span>
      </div>
    </li>
  <% end %>
</ul>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<%- model_class = Photo.new.class -%>
<div class="row-fluid">
  <div id="basket-container" class="span2">
    <% if @basket %>
      <ul>
        <li><%= link_to "Download",
                  {:controller => "baskets", :action => "download", :id => @basket},
                  {:confirm => "Are you sure you would like to download all photos in this basket?", :method => "post"} %></li>
	<li>Drop this basket</li>
      </ul>
    <% else %>
      <h2>Baskets</h2>
      <ul>
	<% @baskets.each do |basket| %>
	  <li class="basket-in-list" id="basket<%= basket.id %>">
            <i class="icon-shopping-cart"></i> <%= link_to basket.name, [ basket, :photos ] %>
          </li>
	<% end %>
      </ul>
    <% end %>
  </div>
  <div class="span10 offset2">
    <%= render 'list' %>

  </div>
</div>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<%- model_class = @photo.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p id="notice"><%= notice %></p>

<p>
  <b>File name:</b>
  <%= File.basename(@photo.full_name) %> <%= link_to "original size",{ :action => 'original_image', :id => @photo.id }, :class => 'btn' %>
</p>

<p>
  <b>Directory:</b>
  <%= @photo.directory.path %>
</p>

<p>
  <%= image_tag url_for(:action => 'inline_image', :id => @photo.id) %>
</p>


<div class="form-actions">
  <%= link_to 'Back', :back, :class => 'btn'  %>
</div>